#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits in the key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $key_bits -f $private_key -N "$passphrase"

